artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_id: 1s-0oJNO2DbpWxIGZ8eEfggq6h1EtWznX
  zip_file: artifacts/data_ingestion/data.zip
  unzip_file: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_file: artifacts/data_ingestion/Fraud-data.csv
  status_file: artifacts/data_validation/status.json

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Fraud-data.csv
  file_status: artifacts/data_validation/status.json
  preprocessor_path: artifacts/data_transformation/preprocess/preprocessor.pkl
  label_encoder: artifacts/data_transformation/preprocess/label_encoders.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_transformation/split/train.csv 
  test_path: artifacts/data_transformation/split/test.csv 
  train_preprocess: artifacts/data_transformation/process/train_processed.npy
  test_preprocess: artifacts/data_transformation/process/test_processed.npy
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_path: artifacts/data_transformation/split/test.csv
  preprocess_path: artifacts/data_transformation/preprocess/preprocessor.pkl
  model_path: artifacts/model_trainer/model.joblib
  metrics_path: artifacts/model_evaluation/metrics.json
  cm_path: artifacts/model_evaluation/cm.png
  roc_path: artifacts/model_evaluation/roc.png
